import { NativeModules } from 'react-native';

type SenseyeSdkType = {
  multiply(a: number, b: number): Promise<number>;
};

const { SenseyeSdk } = NativeModules;

export default SenseyeSdk as SenseyeSdkType;

// TODO: The above code was generated by bob.
//  leaving as reference for now, but will be removed/updated for production

export { VideoRecorder } from './Recorder';
export { ExperimentRunner } from './Runner';
export { Experiments } from './experiments';

export type { VideoRecorderProps } from './Recorder.types';
export type { ExperimentRunnerProps } from './Runner.types';
export type { TestExperimentProps } from './experiments';
